ktor {
    environment = "dev"
    deployment {
        port = 8080
    }

    application {
        modules = [ com.elitec.kingelectronics.ApplicationKt.main ]
    }
}

jwt {
    secret = "secret"
    issuer = "http://0.0.0.0:8080/"
    audience = "http://0.0.0.0:8080/hello"
    realm = "Access to 'hello'"
}

keys {
    google_client = "Client ID"
}

envConfig{
    env = default
    env = ${?ENVIRONMENT}

    default {
        db_url = "https://com.company.superapp.test-123456.firebaseio.com"
        enableTestAccounts = false
        LOG_LEVEL = "INFO"
        LOG_LEVEL = ${?LOG_LEVEL}
    }

    test {
        enableTestAccounts = true
    }

    staging {
        db_url = "https://com.company.superapp.staging-123456.firebaseio.com"
        db_url = ${?DB_URL}
    }

    production {
        db_url = "https://com.company.superapp.prod-123456.firebaseio.com"
        db_url = ${?DB_URL}
    }
}